def get_public_key(private_key: int) -> int: ...
def pedersen_hash(left: int, right: int) -> int: ...
def sign(private_key: int, msg_hash: int, seed: int) -> tuple[int, int]: ...
def verify(public_key: int, msg_hash: int, r: int, s: int) -> bool: ...
def poseidon_hash(x: int, y: int) -> int: ...
def poseidon_hash_single(x: int) -> int: ...
def poseidon_hash_many(inputs: list[int]) -> int: ...
